<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com, contato@sigasmart.com.br
 * https://www.sigasmart.com.br
 */
namespace App\Modules\Councilor\App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use SIGA\Models\AbstractModel;
use SIGA\Scopes\UuidGenerate;

class BoardOfDirector extends AbstractModel
{
    use HasFactory;

    protected $guarded = ['id'];

    public function slugTo()
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function commission_type(){
        return $this->belongsTo(CommissionType::class);
    }
}
