<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com, contato@sigasmart.com.br
 * https://www.sigasmart.com.br
 */

namespace App\Modules\Councilor\App\Providers;


use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;
use SIGA\LivewireComponentsFinder;

class CouncilorServiceProvider extends ServiceProvider
{
    public function register(){
        // TODO: Change the autogenerated stub
    }

    public function boot(){

        $this->loadViewsFrom(app_path('Modules/Councilor/resources/views'), 'admin');

        Blade::componentNamespace('App\\Modules\\Councilor\\App\\View\\Components', 'councilor');
        app(LivewireComponentsFinder::class)->build('App\\Modules\\Councilor\\App\\Http\Livewire','lv-councilor');
    }
}
