<?php
/**
 * Created by Claudio Campos.
 * User: callcocam@gmail.com, contato@sigasmart.com.br
 * https://www.sigasmart.com.br
 */

namespace App\Modules\Admin\App\Providers;


use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;
use SIGA\LivewireComponentsFinder;

class AdminServiceProvider extends ServiceProvider
{

    public function register(){
     // TODO: Change the autogenerated stub
    }

    public function boot(){

        $this->loadViewsFrom(app_path('Modules/Admin/resources/views'), 'admin');

        Blade::componentNamespace('App\\Modules\\Admin\\App\\View\\Components', 'admin');
        app(LivewireComponentsFinder::class)->build('App\\Modules\\Admin\\App\\Http\Livewire','lv-admin');
    }
}
